# Generated by Django 3.0.4 on 2020-04-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alergeno',
            old_name='Icono',
            new_name='icono',
        ),
    ]
