# Generated by Django 3.0.4 on 2020-05-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0005_auto_20200531_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categorias',
        ),
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='receta.Categoria'),
            preserve_default=False,
        ),
    ]
