# Generated by Django 3.0.4 on 2020-06-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfil_categoriassemana'),
        ('receta', '0006_auto_20200531_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil'),
            preserve_default=False,
        ),
    ]
