# Generated by Django 3.0.4 on 2020-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0007_receta_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='dieta',
            field=models.CharField(blank=True, choices=[('o', 'Omnivora'), ('v', 'Vegetariana'), ('n', 'Vegana')], max_length=1, null=True),
        ),
    ]
