# Generated by Django 3.0.4 on 2020-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0008_receta_dieta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergeno',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(default='sin titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruccion',
            name='cantidad',
            field=models.CharField(default='nada', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='dieta',
            field=models.CharField(choices=[('o', 'Omnivora'), ('v', 'Vegetariana'), ('n', 'Vegana')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='kcal',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='minutos_preparacion',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(default='sin titulo', max_length=100),
            preserve_default=False,
        ),
    ]
