# Generated by Django 3.0.4 on 2020-05-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200428_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dieta',
            field=models.CharField(blank=True, choices=[('o', 'Omnivora'), ('v', 'Vegetariana'), ('n', 'Vegana')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='kcal_diarias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
