# Generated by Django 3.0.4 on 2020-05-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0003_auto_20200424_0802'),
        ('perfil', '0003_auto_20200526_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoriasSemana',
            field=models.ManyToManyField(blank=True, related_name='dieta_semanal', to='receta.Categoria'),
        ),
    ]
