# Generated by Django 3.0.4 on 2020-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0008_receta_dieta'),
        ('perfil', '0004_perfil_categoriassemana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(blank=True, null=True, related_name='favoritos_usuarios', to='receta.Receta'),
        ),
    ]
