# Generated by Django 3.0.4 on 2020-06-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20200607_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fotoBg',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/Bg'),
        ),
    ]
