# Generated by Django 3.0.4 on 2020-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receta', '0008_receta_dieta'),
        ('perfil', '0006_perfil_fotobg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos_usuarios', to='receta.Receta'),
        ),
    ]
